apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: groq-servicemonitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack   # âœ… correspond au nom Helm release
spec:
  selector:
    matchLabels:
      app: groq-app
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
